package mythicbotany.world;

import mythicbotany.MythicBotany;
import mythicbotany.registry.ModBlocks;
import mythicbotany.dimension.ModDimensions;
import net.minecraft.block.state.IBlockState;
import net.minecraft.block.Block;
import net.minecraft.block.BlockCrops;
import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraft.tileentity.TileEntity;
import net.minecraft.util.EnumFacing;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.World;
import net.minecraft.world.chunk.IChunkProvider;
import net.minecraft.world.gen.IChunkGenerator;
import net.minecraft.world.gen.feature.WorldGenMinable;
import net.minecraftforge.event.world.ChunkEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.IWorldGenerator;
import vazkii.botania.api.mana.IManaPool;
import vazkii.botania.api.state.BotaniaStateProps;
import vazkii.botania.api.state.enums.PoolVariant;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/** Adds MythicBotany ores to the vanilla overworld generation pipeline. */
@Mod.EventBusSubscriber(modid = MythicBotany.MODID)
public class ModWorldGenerator implements IWorldGenerator {
    private static final IBlockState ELEMENTIUM = ModBlocks.elementiumOre.getDefaultState();
    private static final IBlockState DRAGONSTONE = ModBlocks.dragonstoneOre.getDefaultState();
    private static final IBlockState GOLD = ModBlocks.goldOre.getDefaultState();

    /** Convert chunks generated by older builds to the new surface palette. */
    @SubscribeEvent
    public static void normalizeLegacyAltGrass(ChunkEvent.Load event) {
        if (event.getWorld().isRemote
                || event.getWorld().provider.getDimension() != ModDimensions.ALFHEIM_DIMENSION_ID) {
            return;
        }
        net.minecraft.world.chunk.Chunk chunk = event.getChunk();
        for (int localX = 0; localX < 16; localX++) {
            for (int localZ = 0; localZ < 16; localZ++) {
                for (int y = 0; y < 256; y++) {
                    BlockPos pos = new BlockPos(chunk.x * 16 + localX, y,
                            chunk.z * 16 + localZ);
                    IBlockState state = chunk.getBlockState(pos);
                    if (state.getBlock() == vazkii.botania.common.block.ModBlocks.altGrass
                            && state.getBlock().getMetaFromState(state) != 1) {
                        chunk.setBlockState(pos, Blocks.GRASS.getDefaultState());
                    } else if (isLegacyManaCrystal(event.getWorld(), pos, state)) {
                        normalizeLegacyManaCrystal(event.getWorld(), pos);
                    }
                }
            }
        }
    }

    @Override
    public void generate(Random random, int chunkX, int chunkZ, World world,
                         IChunkGenerator chunkGenerator, IChunkProvider chunkProvider) {
        int dimension = world.provider.getDimension();
        if (dimension == 0) {
            generateOre(world, random, chunkX, chunkZ, ELEMENTIUM, 6, 8, 4, 40,
                    Blocks.STONE);
            generateOre(world, random, chunkX, chunkZ, DRAGONSTONE, 4, 5, 2, 24,
                    Blocks.STONE);
            return;
        }
        if (dimension != ModDimensions.ALFHEIM_DIMENSION_ID) {
            return;
        }

        Block host = vazkii.botania.common.block.ModBlocks.livingrock;
        generateOre(world, random, chunkX, chunkZ, ELEMENTIUM, 6, 8, 4, 40, host);
        generateOre(world, random, chunkX, chunkZ, DRAGONSTONE, 4, 5, 2, 24, host);
        generateOre(world, random, chunkX, chunkZ, GOLD, 8, 8, 8, 48, host);
        generateAlfheimFeatures(world, random, chunkX, chunkZ);
    }

    private void generateOre(World world, Random random, int chunkX, int chunkZ,
                             IBlockState state, int veinSize, int attempts,
                             int minHeight, int maxHeight, Block host) {
        WorldGenMinable generator = new WorldGenMinable(state, veinSize,
                blockState -> blockState.getBlock() == host);
        int heightRange = maxHeight - minHeight;
        for (int attempt = 0; attempt < attempts; attempt++) {
            int x = chunkX * 16 + random.nextInt(16);
            int y = minHeight + random.nextInt(heightRange + 1);
            int z = chunkZ * 16 + random.nextInt(16);
            generator.generate(world, random, new BlockPos(x, y, z));
        }
    }

    private void generateAlfheimFeatures(World world, Random random, int chunkX, int chunkZ) {
        Biome biome = world.getBiome(new BlockPos(chunkX * 16 + 8, 0, chunkZ * 16 + 8));
        // Sample each feature position independently. This prevents tree
        // density from changing in square bands when a biome crosses a chunk.
        // The 1.20 reference uses a rare loose placement and a denser forest
        // placement. These trees are much larger in 1.12, so use a lower
        // probability here to keep the forest readable instead of filling
        // every chunk with overlapping canopies.
        int treeAttempts = 1;
        for (int i = 0; i < treeAttempts; i++) {
            int x = chunkX * 16 + random.nextInt(16);
            int z = chunkZ * 16 + random.nextInt(16);
            Biome treeBiome = world.getBiome(new BlockPos(x, 0, z));
            int chance = treeBiome == AlfheimBiomes.DREAMWOOD_FOREST ? 64
                    : treeBiome == AlfheimBiomes.ALFHEIM_PLAINS ? 43
                    : treeBiome == AlfheimBiomes.ALFHEIM_HILLS ? 54
                    : treeBiome == AlfheimBiomes.GOLDEN_FIELDS ? 64 : 0;
            if (chance > 0 && random.nextInt(chance) == 0
                    && !hasNearbyDreamwood(world, x, z, 10)) {
                generateDreamwoodTree(world, random, x, z);
            }
        }
        if (biome == AlfheimBiomes.DREAMWOOD_FOREST) {
            generateFlowers(world, random, chunkX, chunkZ, 7);
        } else if (biome == AlfheimBiomes.ALFHEIM_PLAINS) {
            generateFlowers(world, random, chunkX, chunkZ, 4);
        } else if (biome == AlfheimBiomes.GOLDEN_FIELDS) {
            generateGoldenField(world, random, chunkX, chunkZ);
        } else if (biome == AlfheimBiomes.ALFHEIM_HILLS) {
            if (random.nextInt(4) == 0) {
                generateManaCrystal(world, random,
                        chunkX * 16 + random.nextInt(16),
                        chunkZ * 16 + random.nextInt(16));
            }
            generateFlowers(world, random, chunkX, chunkZ, 3);
        } else if (biome == AlfheimBiomes.ALFHEIM_LAKES) {
            generateLakePlants(world, random, chunkX, chunkZ);
        }

        if (random.nextInt(biome == AlfheimBiomes.DREAMWOOD_FOREST ? 18 : 28) == 0) {
            generateAbandonedApothecary(world, random, chunkX * 16 + random.nextInt(16),
                    chunkZ * 16 + random.nextInt(16));
        }
    }

    private BlockPos findSolidSurface(World world, int x, int z) {
        BlockPos top = world.getTopSolidOrLiquidBlock(new BlockPos(x, 0, z));
        if (top.getY() <= 0) {
            return null;
        }
        IBlockState topState = world.getBlockState(top);
        // Do not grow land features on top of an ocean or a liquid column.
        if (topState.getMaterial() == Material.WATER
                || topState.getMaterial() == Material.LAVA) {
            return null;
        }
        BlockPos candidate = topState.getMaterial().isSolid() ? top : top.down();
        while (candidate.getY() > 0) {
            if (world.getBlockState(candidate).getMaterial().isSolid()) {
                return candidate;
            }
            candidate = candidate.down();
        }
        return null;
    }

    /**
     * Finds actual terrain below a tree canopy. The old top-solid lookup
     * returned leaves/logs after tree generation, so flowers and wheat were
     * occasionally placed on top of a newly generated tree.
     */
    private BlockPos findGroundSurface(World world, int x, int z) {
        BlockPos top = world.getTopSolidOrLiquidBlock(new BlockPos(x, 0, z));
        for (int y = Math.min(world.getActualHeight() - 1, top.getY()); y > 0; y--) {
            BlockPos pos = new BlockPos(x, y, z);
            IBlockState state = world.getBlockState(pos);
            Block block = state.getBlock();
            if (block == Blocks.GRASS || block == Blocks.DIRT
                    || block == Blocks.FARMLAND || block == Blocks.GRASS_PATH
                    || (block == vazkii.botania.common.block.ModBlocks.altGrass
                    && block.getMetaFromState(state) == 1)) {
                return pos;
            }
            if (block == vazkii.botania.common.block.ModBlocks.dreamwood
                    || block == ModBlocks.dreamwoodLeaves
                    || state.getMaterial() == Material.LEAVES
                    || state.getMaterial() == Material.PLANTS
                    || state.getMaterial() == Material.AIR) {
                continue;
            }
            // Do not tunnel through arbitrary terrain or player structures.
            return null;
        }
        return null;
    }

    private void generateFlowers(World world, Random random, int chunkX, int chunkZ, int count) {
        for (int i = 0; i < count; i++) {
            int x = chunkX * 16 + random.nextInt(16);
            int z = chunkZ * 16 + random.nextInt(16);
            BlockPos surface = findGroundSurface(world, x, z);
            if (surface != null
                    && !hasDreamwoodAbove(world, surface)
                    && world.isAirBlock(surface.up())) {
                world.setBlockState(surface.up(), (i & 1) == 0
                        ? Blocks.RED_FLOWER.getDefaultState()
                        : Blocks.YELLOW_FLOWER.getDefaultState(), 2);
            }
        }
    }

    private void generateGoldenField(World world, Random random, int chunkX, int chunkZ) {
        if (random.nextInt(4) != 0) {
            return;
        }
        int centerX = chunkX * 16 + random.nextInt(12) + 2;
        int centerZ = chunkZ * 16 + random.nextInt(12) + 2;
        int wheatCount = 3 + random.nextInt(6);
        int planted = 0;
        List<BlockPos> plantedPositions = new ArrayList<>();
        int attempts = wheatCount * 8;
        while (planted < wheatCount && attempts-- > 0) {
            int x = centerX + random.nextInt(5) - 2;
            int z = centerZ + random.nextInt(5) - 2;
            BlockPos surface = findGroundSurface(world, x, z);
            if (surface != null && !hasDreamwoodAbove(world, surface)
                    && world.isAirBlock(surface.up())
                    && isValidWheatGround(world, surface)
                    && !plantedPositions.contains(surface)) {
                world.setBlockState(surface, Blocks.FARMLAND.getDefaultState(), 2);
                world.setBlockState(surface.up(), Blocks.WHEAT.getDefaultState()
                        .withProperty(BlockCrops.AGE, 7), 2);
                plantedPositions.add(surface);
                planted++;
            }
        }
    }

    private boolean isValidWheatGround(World world, BlockPos surface) {
        IBlockState state = world.getBlockState(surface);
        return state.getBlock() == Blocks.GRASS || state.getBlock() == Blocks.DIRT
                || (state.getBlock() == vazkii.botania.common.block.ModBlocks.altGrass
                && state.getBlock().getMetaFromState(state) == 1);
    }

    private boolean generateManaCrystal(World world, Random random, int x, int z) {
        BlockPos surface = findGroundSurface(world, x, z);
        if (surface == null) {
            return false;
        }
        for (EnumFacing direction : EnumFacing.HORIZONTALS) {
            if (!world.getBlockState(surface.offset(direction)).getMaterial().isSolid()) {
                return false;
            }
        }

        BlockPos origin = surface.up();
        int mainHeight = 5 + random.nextInt(5);
        List<BlockPos> crystalBlocks = new ArrayList<>();
        for (int y = 2; y < mainHeight; y++) {
            crystalBlocks.add(origin.up(y));
        }
        for (EnumFacing direction : EnumFacing.HORIZONTALS) {
            BlockPos branch = origin.offset(direction);
            int height = 2 + random.nextInt(Math.max(1, mainHeight - 4));
            for (int y = 0; y < height; y++) {
                crystalBlocks.add(branch.up(y));
            }
        }
        if (!world.isAirBlock(origin)) {
            return false;
        }
        for (BlockPos pos : crystalBlocks) {
            if (!canReplaceCrystalBlock(world, pos)) {
                return false;
            }
        }

        // This is the 1.12 equivalent of MythicBotany's diluted mana pool
        // crystal: a diluted pool stores the generated mana while bifrost
        // pillars form the visible crystal around it.
        IBlockState pool = getDilutedPoolState();
        if (pool == null) {
            return false;
        }
        world.setBlockState(origin, pool, 2);
        TileEntity tile = world.getTileEntity(origin);
        if (!(tile instanceof IManaPool)) {
            world.setBlockToAir(origin);
            return false;
        }
        ((IManaPool) tile).recieveMana(10 + random.nextInt(490));

        IBlockState crystal = vazkii.botania.common.block.ModBlocks.bifrostPerm.getDefaultState();
        for (BlockPos pos : crystalBlocks) {
            world.setBlockState(pos, crystal, 2);
        }
        return true;
    }

    /** Resolve the diluted variant by its state name instead of assuming that
     * every Botania 1.12 build uses the same metadata ordering. */
    private static IBlockState getDilutedPoolState() {
        return vazkii.botania.common.block.ModBlocks.pool.getDefaultState()
                .withProperty(BotaniaStateProps.POOL_VARIANT, PoolVariant.DILUTED);
    }

    /**
     * Older builds generated mana crystals with a creative pool at the
     * centre. Convert only the distinctive crystal shape, never arbitrary
     * creative pools placed by a player.
     */
    private static boolean isLegacyManaCrystal(World world, BlockPos pos,
                                               IBlockState state) {
        if (state.getBlock() != vazkii.botania.common.block.ModBlocks.pool
                || state.getValue(BotaniaStateProps.POOL_VARIANT) != PoolVariant.CREATIVE
                || !world.isAirBlock(pos.up())
                || world.getBlockState(pos.up(2)).getBlock()
                != vazkii.botania.common.block.ModBlocks.bifrostPerm) {
            return false;
        }
        for (EnumFacing direction : EnumFacing.HORIZONTALS) {
            if (world.getBlockState(pos.offset(direction)).getBlock()
                    != vazkii.botania.common.block.ModBlocks.bifrostPerm) {
                return false;
            }
        }
        return true;
    }

    private static void normalizeLegacyManaCrystal(World world, BlockPos pos) {
        int existingMana = 0;
        TileEntity oldTile = world.getTileEntity(pos);
        if (oldTile instanceof IManaPool) {
            existingMana = ((IManaPool) oldTile).getCurrentMana();
        }

        world.setBlockState(pos, getDilutedPoolState(), 3);
        TileEntity newTile = world.getTileEntity(pos);
        if (newTile instanceof IManaPool) {
            int mana = Math.max(10, Math.min(490, existingMana));
            ((IManaPool) newTile).recieveMana(mana);
        }
    }

    private boolean hasNearbyDreamwood(World world, int x, int z, int radius) {
        for (int dx = -radius; dx <= radius; dx += 2) {
            for (int dz = -radius; dz <= radius; dz += 2) {
                int sampleX = x + dx;
                int sampleZ = z + dz;
                BlockPos top = world.getTopSolidOrLiquidBlock(
                        new BlockPos(sampleX, 0, sampleZ));
                for (int y = top.getY(); y > 0; y--) {
                    Block block = world.getBlockState(
                            new BlockPos(sampleX, y, sampleZ)).getBlock();
                    if (block == vazkii.botania.common.block.ModBlocks.dreamwood
                            || block == ModBlocks.dreamwoodLeaves) {
                        return true;
                    }
                    if (block == Blocks.GRASS || block == Blocks.DIRT
                            || block == Blocks.FARMLAND) {
                        break;
                    }
                }
            }
        }
        return false;
    }

    private boolean hasDreamwoodAbove(World world, BlockPos ground) {
        for (int y = ground.getY() + 1; y < world.getActualHeight(); y++) {
            IBlockState state = world.getBlockState(
                    new BlockPos(ground.getX(), y, ground.getZ()));
            Block block = state.getBlock();
            if (block == vazkii.botania.common.block.ModBlocks.dreamwood
                    || block == ModBlocks.dreamwoodLeaves
                    || state.getMaterial() == Material.LEAVES) {
                return true;
            }
        }
        return false;
    }

    private boolean canReplaceCrystalBlock(World world, BlockPos pos) {
        IBlockState state = world.getBlockState(pos);
        return world.isAirBlock(pos)
                || state.getMaterial() == Material.LEAVES
                || state.getMaterial() == Material.PLANTS
                || state.getMaterial() == Material.WATER;
    }

    private void generateLakePlants(World world, Random random, int chunkX, int chunkZ) {
        for (int i = 0; i < 3; i++) {
            int x = chunkX * 16 + random.nextInt(16);
            int z = chunkZ * 16 + random.nextInt(16);
            BlockPos surface = world.getTopSolidOrLiquidBlock(new BlockPos(x, 0, z));
            if (world.getBlockState(surface).getBlock() == Blocks.WATER
                    && world.isAirBlock(surface.up())) {
                world.setBlockState(surface.up(), Blocks.WATERLILY.getDefaultState(), 2);
            }
        }
    }

    private void generateDreamwoodTree(World world, Random random, int x, int z) {
        BlockPos surface = findGroundSurface(world, x, z);
        if (surface == null) {
            return;
        }
        IBlockState ground = world.getBlockState(surface);
        if (ground.getBlock() != Blocks.GRASS && ground.getBlock() != Blocks.DIRT) {
            return;
        }
        // Port of MythicBotany's ShatteredTrunkPlacer and RandomFoliagePlacer
        // for the 1.12 generator: a tall trunk, hanging roots, broken limbs,
        // and small irregular leaf clusters.
        BlockPos base = surface.up();
        int height = 7 + random.nextInt(5);
        int straightTrunkSize = Math.max(3, height - 3);
        IBlockState log = vazkii.botania.common.block.ModBlocks.dreamwood.getDefaultState();
        for (int i = 0; i < straightTrunkSize; i++) {
            if (!canReplaceDreamwood(world, base.up(i))) {
                return;
            }
        }
        for (int i = 0; i < straightTrunkSize; i++) {
            world.setBlockState(base.up(i), log, 2);
        }

        for (EnumFacing direction : EnumFacing.HORIZONTALS) {
            if (random.nextInt(3) != 0) {
                continue;
            }
            BlockPos root = base.offset(direction);
            for (int i = 0; i < 3; i++) {
                if (!placeDreamwoodLog(world, root, log)) {
                    break;
                }
                root = root.down();
            }
        }

        List<BlockPos> foliageAttachments = new ArrayList<>();
        BlockPos branchTop = base.up(straightTrunkSize - 1);
        int shatters = 3 + random.nextInt(3);
        for (int branchIndex = 0; branchIndex < shatters; branchIndex++) {
            int xDistance = random.nextInt(3);
            int zDistance = random.nextInt(3);
            int xSign = random.nextBoolean() ? 1 : -1;
            int zSign = random.nextBoolean() ? 1 : -1;
            BlockPos branch = branchTop;
            boolean failed = false;
            int branchSize = 3 + random.nextInt(4);
            for (int segment = 0; segment < branchSize && !failed; segment++) {
                int targetX = xDistance == 0 ? 0
                        : xDistance / 2 + random.nextInt((xDistance + 1) / 2);
                int targetZ = zDistance == 0 ? 0
                        : zDistance / 2 + random.nextInt((zDistance + 1) / 2);
                int movedX = 0;
                int movedZ = 0;
                while (movedX < targetX || movedZ < targetZ) {
                    int stepX = movedX < targetX ? xSign : 0;
                    int stepZ = movedZ < targetZ ? zSign : 0;
                    int stepY = random.nextInt(3) != 0 ? 1 : 0;
                    branch = branch.add(stepX, stepY, stepZ);
                    movedX = Math.min(targetX, movedX + 1);
                    movedZ = Math.min(targetZ, movedZ + 1);
                    if (!placeDreamwoodLog(world, branch, log)) {
                        failed = true;
                        break;
                    }
                    foliageAttachments.add(branch);
                }
            }
        }

        if (foliageAttachments.isEmpty()) {
            foliageAttachments.add(branchTop);
        }
        IBlockState leaves = ModBlocks.dreamwoodLeaves.getDefaultState();
        for (BlockPos attachment : foliageAttachments) {
            placeDreamwoodFoliage(world, random, attachment, leaves);
        }
    }

    private boolean canReplaceDreamwood(World world, BlockPos pos) {
        IBlockState state = world.getBlockState(pos);
        return world.isAirBlock(pos)
                || state.getMaterial() == Material.LEAVES
                || state.getMaterial() == Material.PLANTS
                || state.getMaterial() == Material.WATER
                || state.getBlock() == ModBlocks.dreamwoodLeaves;
    }

    private boolean placeDreamwoodLog(World world, BlockPos pos, IBlockState log) {
        if (!canReplaceDreamwood(world, pos)) {
            return false;
        }
        world.setBlockState(pos, log, 2);
        return true;
    }

    private void placeDreamwoodFoliage(World world, Random random, BlockPos attachment,
                                       IBlockState leaves) {
        int leafCount = 3 + random.nextInt(3);
        for (int i = 0; i < leafCount; i++) {
            int x = random.nextInt(5) - 2;
            int y = random.nextInt(5) - 2;
            int z = random.nextInt(5) - 2;
            BlockPos leaf = attachment.add(x, y, z);
            if (canReplaceDreamwood(world, leaf)) {
                world.setBlockState(leaf, leaves, 2);
                int nearX = x == 0 ? 0 : x > 0 ? x - 1 : x + 1;
                int nearY = y == 0 ? 0 : y > 0 ? y - 1 : y + 1;
                int nearZ = z == 0 ? 0 : z > 0 ? z - 1 : z + 1;
                BlockPos nearbyLeaf = attachment.add(nearX, nearY, nearZ);
                if (canReplaceDreamwood(world, nearbyLeaf)) {
                    world.setBlockState(nearbyLeaf, leaves, 2);
                }
            }
        }
    }

    private void generateAbandonedApothecary(World world, Random random, int x, int z) {
        BlockPos surface = world.getTopSolidOrLiquidBlock(new BlockPos(x, 0, z));
        if (!world.getBlockState(surface).getMaterial().isSolid()
                || !world.isAirBlock(surface.up())) {
            return;
        }
        BlockPos base = surface.up();
        vazkii.botania.api.state.enums.AltarVariant variant =
                vazkii.botania.api.state.enums.AltarVariant.values()[
                        random.nextInt(vazkii.botania.api.state.enums.AltarVariant.values().length)];
        IBlockState altarState = vazkii.botania.common.block.ModBlocks.altar.getDefaultState()
                .withProperty(BotaniaStateProps.ALTAR_VARIANT, variant);
        world.setBlockState(base, altarState, 2);
        IBlockState wood = vazkii.botania.common.block.ModBlocks.livingwood.getDefaultState();
        for (int dx = -1; dx <= 1; dx++) {
            for (int dz = -1; dz <= 1; dz++) {
                if (dx != 0 || dz != 0) {
                    BlockPos pos = base.add(dx, 0, dz);
                    if (world.isAirBlock(pos)) {
                        world.setBlockState(pos, wood, 2);
                    }
                }
            }
        }

        TileEntity tile = world.getTileEntity(base);
        if (!(tile instanceof vazkii.botania.common.block.tile.TileAltar)) {
            return;
        }
        vazkii.botania.common.block.tile.TileAltar altar =
                (vazkii.botania.common.block.tile.TileAltar) tile;
        if (random.nextInt(30) == 0) {
            altar.setLava(true);
        } else if (random.nextInt(4) != 0) {
            altar.setWater(true);
            int petals = random.nextInt(5);
            for (int slot = 0; slot < petals; slot++) {
                altar.getItemHandler().setStackInSlot(slot,
                        new net.minecraft.item.ItemStack(
                                vazkii.botania.common.item.ModItems.petal, 1,
                                random.nextInt(16)));
            }
        }
    }
}
