package mythicbotany.world;

import mythicbotany.MythicBotany;
import mythicbotany.registry.ModBlocks;
import mythicbotany.registry.ModItems;
import mythicbotany.dimension.ModDimensions;
import net.minecraft.block.state.IBlockState;
import net.minecraft.block.Block;
import net.minecraft.block.BlockChest;
import net.minecraft.block.BlockCrops;
import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.tileentity.TileEntity;
import net.minecraft.tileentity.TileEntityChest;
import net.minecraft.util.EnumFacing;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.World;
import net.minecraft.world.chunk.IChunkProvider;
import net.minecraft.world.gen.IChunkGenerator;
import net.minecraft.world.gen.feature.WorldGenMinable;
import net.minecraftforge.event.world.ChunkEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.IWorldGenerator;
import vazkii.botania.api.mana.IManaPool;
import vazkii.botania.api.state.BotaniaStateProps;
import vazkii.botania.api.state.enums.PoolVariant;
import vazkii.botania.common.block.tile.mana.TilePool;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/** Adds MythicBotany ores to the vanilla overworld generation pipeline. */
@Mod.EventBusSubscriber(modid = MythicBotany.MODID)
public class ModWorldGenerator implements IWorldGenerator {
    private static final IBlockState ELEMENTIUM = ModBlocks.elementiumOre.getDefaultState();
    private static final IBlockState DRAGONSTONE = ModBlocks.dragonstoneOre.getDefaultState();
    private static final IBlockState GOLD = ModBlocks.goldOre.getDefaultState();

    /** Convert chunks generated by older builds to the new surface palette. */
    @SubscribeEvent
    public static void normalizeLegacyAltGrass(ChunkEvent.Load event) {
        if (event.getWorld().isRemote
                || event.getWorld().provider.getDimension() != ModDimensions.ALFHEIM_DIMENSION_ID) {
            return;
        }
        net.minecraft.world.chunk.Chunk chunk = event.getChunk();
        for (int localX = 0; localX < 16; localX++) {
            for (int localZ = 0; localZ < 16; localZ++) {
                for (int y = 0; y < 256; y++) {
                    BlockPos pos = new BlockPos(chunk.x * 16 + localX, y,
                            chunk.z * 16 + localZ);
                    IBlockState state = chunk.getBlockState(pos);
                    if (state.getBlock() == vazkii.botania.common.block.ModBlocks.altGrass
                            && state.getBlock().getMetaFromState(state) != 1) {
                        chunk.setBlockState(pos, Blocks.GRASS.getDefaultState());
                    } else if (isLegacyManaCrystal(event.getWorld(), pos, state)) {
                        normalizeLegacyManaCrystal(event.getWorld(), pos);
                    }
                }
            }
        }
    }

    @Override
    public void generate(Random random, int chunkX, int chunkZ, World world,
                         IChunkGenerator chunkGenerator, IChunkProvider chunkProvider) {
        int dimension = world.provider.getDimension();
        if (dimension == 0) {
            generateOre(world, random, chunkX, chunkZ, ELEMENTIUM, 6, 8, 4, 40,
                    Blocks.STONE);
            generateOre(world, random, chunkX, chunkZ, DRAGONSTONE, 4, 5, 2, 24,
                    Blocks.STONE);
            return;
        }
        if (dimension != ModDimensions.ALFHEIM_DIMENSION_ID) {
            return;
        }

        Block host = vazkii.botania.common.block.ModBlocks.livingrock;
        generateOre(world, random, chunkX, chunkZ, ELEMENTIUM, 6, 8, 4, 40, host);
        generateOre(world, random, chunkX, chunkZ, DRAGONSTONE, 4, 5, 2, 24, host);
        generateOre(world, random, chunkX, chunkZ, GOLD, 8, 8, 8, 48, host);
        generateAlfheimFeatures(world, random, chunkX, chunkZ);
    }

    private void generateOre(World world, Random random, int chunkX, int chunkZ,
                             IBlockState state, int veinSize, int attempts,
                             int minHeight, int maxHeight, Block host) {
        WorldGenMinable generator = new WorldGenMinable(state, veinSize,
                blockState -> blockState.getBlock() == host);
        int heightRange = maxHeight - minHeight;
        for (int attempt = 0; attempt < attempts; attempt++) {
            int x = chunkX * 16 + random.nextInt(16);
            int y = minHeight + random.nextInt(heightRange + 1);
            int z = chunkZ * 16 + random.nextInt(16);
            generator.generate(world, random, new BlockPos(x, y, z));
        }
    }

    private void generateAlfheimFeatures(World world, Random random, int chunkX, int chunkZ) {
        Biome biome = world.getBiome(new BlockPos(chunkX * 16 + 8, 0, chunkZ * 16 + 8));
        // Sample each feature position independently. This prevents tree
        // density from changing in square bands when a biome crosses a chunk.
        // The 1.20 reference uses a rare loose placement and a denser forest
        // placement. These trees are much larger in 1.12, so use a lower
        // probability here to keep the forest readable instead of filling
        // every chunk with overlapping canopies.
        // db44772 used six samples per chunk. Its old non-forest rates were
        // 1/5 in plains and 1/8 in hills. Keep those rates as the reference:
        // forests use the old plains rate, while other biomes use one fifth
        // of their old non-forest rate.
        int treeAttempts = 6;
        for (int i = 0; i < treeAttempts; i++) {
            int x = chunkX * 16 + random.nextInt(16);
            int z = chunkZ * 16 + random.nextInt(16);
            Biome treeBiome = world.getBiome(new BlockPos(x, 0, z));
            int chance = treeBiome == AlfheimBiomes.DREAMWOOD_FOREST ? 5
                    : treeBiome == AlfheimBiomes.ALFHEIM_PLAINS ? 25
                    : treeBiome == AlfheimBiomes.ALFHEIM_HILLS ? 40
                    : treeBiome == AlfheimBiomes.GOLDEN_FIELDS ? 40 : 0;
            if (chance > 0 && random.nextInt(chance) == 0
                    && !hasNearbyDreamwood(world, x, z, 6)) {
                generateDreamwoodTree(world, random, x, z);
            }
        }
        if (biome == AlfheimBiomes.DREAMWOOD_FOREST) {
            generateFlowers(world, random, chunkX, chunkZ, 7);
        } else if (biome == AlfheimBiomes.ALFHEIM_PLAINS) {
            generateFlowers(world, random, chunkX, chunkZ, 4);
        } else if (biome == AlfheimBiomes.GOLDEN_FIELDS) {
            generateGoldenField(world, random, chunkX, chunkZ);
        } else if (biome == AlfheimBiomes.ALFHEIM_HILLS) {
            if (random.nextInt(4) == 0) {
                generateManaCrystal(world, random,
                        chunkX * 16 + random.nextInt(16),
                        chunkZ * 16 + random.nextInt(16));
            }
            generateFlowers(world, random, chunkX, chunkZ, 3);
        } else if (biome == AlfheimBiomes.ALFHEIM_LAKES) {
            generateLakePlants(world, random, chunkX, chunkZ);
        }

        if (biome == AlfheimBiomes.GOLDEN_FIELDS
                && isAndwariCaveChunk(world, chunkX, chunkZ)) {
            generateAndwariCave(world, random, chunkX, chunkZ);
        }

        if (random.nextInt(20) == 0) {
            for (int attempt = 0; attempt < 4; attempt++) {
                if (generateAbandonedApothecary(world, random,
                        chunkX * 16 + random.nextInt(16),
                        chunkZ * 16 + random.nextInt(16))) {
                    break;
                }
            }
        }
    }

    private BlockPos findSolidSurface(World world, int x, int z) {
        BlockPos top = world.getTopSolidOrLiquidBlock(new BlockPos(x, 0, z));
        if (top.getY() <= 0) {
            return null;
        }
        IBlockState topState = world.getBlockState(top);
        // Do not grow land features on top of an ocean or a liquid column.
        if (topState.getMaterial() == Material.WATER
                || topState.getMaterial() == Material.LAVA) {
            return null;
        }
        BlockPos candidate = topState.getMaterial().isSolid() ? top : top.down();
        while (candidate.getY() > 0) {
            if (world.getBlockState(candidate).getMaterial().isSolid()) {
                return candidate;
            }
            candidate = candidate.down();
        }
        return null;
    }

    /**
     * Finds actual terrain below a tree canopy. The old top-solid lookup
     * returned leaves/logs after tree generation, so flowers and wheat were
     * occasionally placed on top of a newly generated tree.
     */
    private BlockPos findGroundSurface(World world, int x, int z) {
        BlockPos top = world.getTopSolidOrLiquidBlock(new BlockPos(x, 0, z));
        for (int y = Math.min(world.getActualHeight() - 1, top.getY()); y > 0; y--) {
            BlockPos pos = new BlockPos(x, y, z);
            IBlockState state = world.getBlockState(pos);
            Block block = state.getBlock();
            if (block == Blocks.GRASS || block == Blocks.DIRT
                    || block == Blocks.FARMLAND || block == Blocks.GRASS_PATH
                    || (block == vazkii.botania.common.block.ModBlocks.altGrass
                    && block.getMetaFromState(state) == 1)) {
                return pos;
            }
            if (block == vazkii.botania.common.block.ModBlocks.dreamwood
                    || block == ModBlocks.dreamwoodLeaves
                    || state.getMaterial() == Material.LEAVES
                    || state.getMaterial() == Material.PLANTS
                    || state.getMaterial() == Material.AIR) {
                continue;
            }
            // Do not tunnel through arbitrary terrain or player structures.
            return null;
        }
        return null;
    }

    private void generateFlowers(World world, Random random, int chunkX, int chunkZ, int count) {
        for (int i = 0; i < count; i++) {
            int x = chunkX * 16 + random.nextInt(16);
            int z = chunkZ * 16 + random.nextInt(16);
            BlockPos surface = findGroundSurface(world, x, z);
            if (surface != null
                    && !hasDreamwoodAbove(world, surface)
                    && world.isAirBlock(surface.up())) {
                world.setBlockState(surface.up(), (i & 1) == 0
                        ? Blocks.RED_FLOWER.getDefaultState()
                        : Blocks.YELLOW_FLOWER.getDefaultState(), 2);
            }
        }
    }

    private void generateGoldenField(World world, Random random, int chunkX, int chunkZ) {
        if (random.nextInt(4) != 0) {
            return;
        }
        int centerX = chunkX * 16 + random.nextInt(12) + 2;
        int centerZ = chunkZ * 16 + random.nextInt(12) + 2;
        int wheatCount = 3 + random.nextInt(6);
        int planted = 0;
        List<BlockPos> plantedPositions = new ArrayList<>();
        int attempts = wheatCount * 8;
        while (planted < wheatCount && attempts-- > 0) {
            int x = centerX + random.nextInt(5) - 2;
            int z = centerZ + random.nextInt(5) - 2;
            BlockPos surface = findGroundSurface(world, x, z);
            if (surface != null && !hasDreamwoodAbove(world, surface)
                    && world.isAirBlock(surface.up())
                    && isValidWheatGround(world, surface)
                    && !plantedPositions.contains(surface)) {
                world.setBlockState(surface, Blocks.FARMLAND.getDefaultState(), 2);
                world.setBlockState(surface.up(), Blocks.WHEAT.getDefaultState()
                        .withProperty(BlockCrops.AGE, 7), 2);
                plantedPositions.add(surface);
                planted++;
            }
        }
    }

    private boolean isValidWheatGround(World world, BlockPos surface) {
        IBlockState state = world.getBlockState(surface);
        return state.getBlock() == Blocks.GRASS || state.getBlock() == Blocks.DIRT
                || (state.getBlock() == vazkii.botania.common.block.ModBlocks.altGrass
                && state.getBlock().getMetaFromState(state) == 1);
    }

    private boolean generateManaCrystal(World world, Random random, int x, int z) {
        BlockPos surface = findGroundSurface(world, x, z);
        if (surface == null) {
            return false;
        }
        for (EnumFacing direction : EnumFacing.HORIZONTALS) {
            if (!world.getBlockState(surface.offset(direction)).getMaterial().isSolid()) {
                return false;
            }
        }

        BlockPos origin = surface.up();
        int mainHeight = 5 + random.nextInt(5);
        List<BlockPos> crystalBlocks = new ArrayList<>();
        for (int y = 2; y < mainHeight; y++) {
            crystalBlocks.add(origin.up(y));
        }
        for (EnumFacing direction : EnumFacing.HORIZONTALS) {
            BlockPos branch = origin.offset(direction);
            int height = 2 + random.nextInt(Math.max(1, mainHeight - 4));
            for (int y = 0; y < height; y++) {
                crystalBlocks.add(branch.up(y));
            }
        }
        if (!world.isAirBlock(origin)) {
            return false;
        }
        for (BlockPos pos : crystalBlocks) {
            if (!canReplaceCrystalBlock(world, pos)) {
                return false;
            }
        }

        // This is the 1.12 equivalent of MythicBotany's diluted mana pool
        // crystal: a diluted pool stores the generated mana while bifrost
        // pillars form the visible crystal around it.
        IBlockState pool = getDilutedPoolState();
        if (pool == null) {
            return false;
        }
        world.setBlockState(origin, pool, 2);
        TileEntity tile = world.getTileEntity(origin);
        if (!initializeDilutedManaPool(tile, 10 + random.nextInt(490))) {
            world.setBlockToAir(origin);
            return false;
        }

        IBlockState crystal = vazkii.botania.common.block.ModBlocks.bifrostPerm.getDefaultState();
        for (BlockPos pos : crystalBlocks) {
            world.setBlockState(pos, crystal, 2);
        }
        return true;
    }

    /** Resolve the diluted variant by its state name instead of assuming that
     * every Botania 1.12 build uses the same metadata ordering. */
    private static IBlockState getDilutedPoolState() {
        return vazkii.botania.common.block.ModBlocks.pool.getDefaultState()
                .withProperty(BotaniaStateProps.POOL_VARIANT, PoolVariant.DILUTED);
    }

    /**
     * Older builds generated mana crystals with a creative pool at the
     * centre. Convert only the distinctive crystal shape, never arbitrary
     * creative pools placed by a player.
     */
    private static boolean isLegacyManaCrystal(World world, BlockPos pos,
                                               IBlockState state) {
        if (state.getBlock() != vazkii.botania.common.block.ModBlocks.pool
                || state.getValue(BotaniaStateProps.POOL_VARIANT) != PoolVariant.CREATIVE
                || !world.isAirBlock(pos.up())
                || world.getBlockState(pos.up(2)).getBlock()
                != vazkii.botania.common.block.ModBlocks.bifrostPerm) {
            return false;
        }
        for (EnumFacing direction : EnumFacing.HORIZONTALS) {
            if (world.getBlockState(pos.offset(direction)).getBlock()
                    != vazkii.botania.common.block.ModBlocks.bifrostPerm) {
                return false;
            }
        }
        return true;
    }

    private static void normalizeLegacyManaCrystal(World world, BlockPos pos) {
        int existingMana = 0;
        TileEntity oldTile = world.getTileEntity(pos);
        if (oldTile instanceof IManaPool) {
            existingMana = ((IManaPool) oldTile).getCurrentMana();
        }

        world.setBlockState(pos, getDilutedPoolState(), 3);
        TileEntity newTile = world.getTileEntity(pos);
        int mana = Math.max(10, Math.min(490, existingMana));
        initializeDilutedManaPool(newTile, mana);
    }

    /** Initialize the diluted pool's cap before receiving mana. TilePool
     * normally fills this field during its first tick, which is too late for
     * worldgen: recieveMana would otherwise clamp against -1 and store zero. */
    private static boolean initializeDilutedManaPool(TileEntity tile, int mana) {
        if (!(tile instanceof TilePool) || !(tile instanceof IManaPool)) {
            return false;
        }
        NBTTagCompound data = new NBTTagCompound();
        data.setInteger("manaCap", TilePool.MAX_MANA_DILLUTED);
        data.setInteger("mana", 0);
        ((TilePool) tile).readPacketNBT(data);
        ((IManaPool) tile).recieveMana(Math.max(1, mana));
        return ((IManaPool) tile).getCurrentMana() > 0;
    }

    private boolean hasNearbyDreamwood(World world, int x, int z, int radius) {
        for (int dx = -radius; dx <= radius; dx += 2) {
            for (int dz = -radius; dz <= radius; dz += 2) {
                int sampleX = x + dx;
                int sampleZ = z + dz;
                BlockPos top = world.getTopSolidOrLiquidBlock(
                        new BlockPos(sampleX, 0, sampleZ));
                for (int y = top.getY(); y > 0; y--) {
                    Block block = world.getBlockState(
                            new BlockPos(sampleX, y, sampleZ)).getBlock();
                    if (block == vazkii.botania.common.block.ModBlocks.dreamwood
                            || block == ModBlocks.dreamwoodLeaves) {
                        return true;
                    }
                    if (block == Blocks.GRASS || block == Blocks.DIRT
                            || block == Blocks.FARMLAND) {
                        break;
                    }
                }
            }
        }
        return false;
    }

    private boolean hasDreamwoodAbove(World world, BlockPos ground) {
        for (int y = ground.getY() + 1; y < world.getActualHeight(); y++) {
            IBlockState state = world.getBlockState(
                    new BlockPos(ground.getX(), y, ground.getZ()));
            Block block = state.getBlock();
            if (block == vazkii.botania.common.block.ModBlocks.dreamwood
                    || block == ModBlocks.dreamwoodLeaves
                    || state.getMaterial() == Material.LEAVES) {
                return true;
            }
        }
        return false;
    }

    private boolean canReplaceCrystalBlock(World world, BlockPos pos) {
        IBlockState state = world.getBlockState(pos);
        return world.isAirBlock(pos)
                || state.getMaterial() == Material.LEAVES
                || state.getMaterial() == Material.PLANTS
                || state.getMaterial() == Material.WATER;
    }

    private void generateLakePlants(World world, Random random, int chunkX, int chunkZ) {
        for (int i = 0; i < 3; i++) {
            int x = chunkX * 16 + random.nextInt(16);
            int z = chunkZ * 16 + random.nextInt(16);
            BlockPos surface = world.getTopSolidOrLiquidBlock(new BlockPos(x, 0, z));
            if (world.getBlockState(surface).getBlock() == Blocks.WATER
                    && world.isAirBlock(surface.up())) {
                world.setBlockState(surface.up(), Blocks.WATERLILY.getDefaultState(), 2);
            }
        }
    }

    private void generateDreamwoodTree(World world, Random random, int x, int z) {
        BlockPos surface = findGroundSurface(world, x, z);
        if (surface == null) {
            return;
        }
        IBlockState ground = world.getBlockState(surface);
        if (ground.getBlock() != Blocks.GRASS && ground.getBlock() != Blocks.DIRT) {
            return;
        }
        // Port of MythicBotany's ShatteredTrunkPlacer and RandomFoliagePlacer
        // for the 1.12 generator: a tall trunk, hanging roots, broken limbs,
        // and small irregular leaf clusters.
        BlockPos base = surface.up();
        int height = 7 + random.nextInt(5);
        int straightTrunkSize = Math.max(3, height - 3);
        IBlockState log = vazkii.botania.common.block.ModBlocks.dreamwood.getDefaultState();
        for (int i = 0; i < straightTrunkSize; i++) {
            if (!canReplaceDreamwood(world, base.up(i))) {
                return;
            }
        }
        for (int i = 0; i < straightTrunkSize; i++) {
            world.setBlockState(base.up(i), log, 2);
        }

        for (EnumFacing direction : EnumFacing.HORIZONTALS) {
            if (random.nextInt(3) != 0) {
                continue;
            }
            BlockPos root = base.offset(direction);
            for (int i = 0; i < 3; i++) {
                if (!placeDreamwoodLog(world, root, log)) {
                    break;
                }
                root = root.down();
            }
        }

        List<BlockPos> foliageAttachments = new ArrayList<>();
        BlockPos branchTop = base.up(straightTrunkSize - 1);
        int shatters = 3 + random.nextInt(3);
        for (int branchIndex = 0; branchIndex < shatters; branchIndex++) {
            int xDistance = random.nextInt(3);
            int zDistance = random.nextInt(3);
            int xSign = random.nextBoolean() ? 1 : -1;
            int zSign = random.nextBoolean() ? 1 : -1;
            BlockPos branch = branchTop;
            boolean failed = false;
            int branchSize = 3 + random.nextInt(4);
            for (int segment = 0; segment < branchSize && !failed; segment++) {
                int targetX = xDistance == 0 ? 0
                        : xDistance / 2 + random.nextInt((xDistance + 1) / 2);
                int targetZ = zDistance == 0 ? 0
                        : zDistance / 2 + random.nextInt((zDistance + 1) / 2);
                int movedX = 0;
                int movedZ = 0;
                while (movedX < targetX || movedZ < targetZ) {
                    int stepX = movedX < targetX ? xSign : 0;
                    int stepZ = movedZ < targetZ ? zSign : 0;
                    int stepY = random.nextInt(3) != 0 ? 1 : 0;
                    branch = branch.add(stepX, stepY, stepZ);
                    movedX = Math.min(targetX, movedX + 1);
                    movedZ = Math.min(targetZ, movedZ + 1);
                    if (!placeDreamwoodLog(world, branch, log)) {
                        failed = true;
                        break;
                    }
                    foliageAttachments.add(branch);
                }
            }
        }

        if (foliageAttachments.isEmpty()) {
            foliageAttachments.add(branchTop);
        }
        IBlockState leaves = ModBlocks.dreamwoodLeaves.getDefaultState();
        for (BlockPos attachment : foliageAttachments) {
            placeDreamwoodFoliage(world, random, attachment, leaves);
        }
    }

    private boolean canReplaceDreamwood(World world, BlockPos pos) {
        IBlockState state = world.getBlockState(pos);
        return world.isAirBlock(pos)
                || state.getMaterial() == Material.LEAVES
                || state.getMaterial() == Material.PLANTS
                || state.getMaterial() == Material.WATER
                || state.getBlock() == ModBlocks.dreamwoodLeaves;
    }

    private boolean placeDreamwoodLog(World world, BlockPos pos, IBlockState log) {
        if (!canReplaceDreamwood(world, pos)) {
            return false;
        }
        world.setBlockState(pos, log, 2);
        return true;
    }

    private void placeDreamwoodFoliage(World world, Random random, BlockPos attachment,
                                       IBlockState leaves) {
        int leafCount = 3 + random.nextInt(3);
        for (int i = 0; i < leafCount; i++) {
            int x = random.nextInt(5) - 2;
            int y = random.nextInt(5) - 2;
            int z = random.nextInt(5) - 2;
            BlockPos leaf = attachment.add(x, y, z);
            if (canReplaceDreamwood(world, leaf)) {
                world.setBlockState(leaf, leaves, 2);
                int nearX = x == 0 ? 0 : x > 0 ? x - 1 : x + 1;
                int nearY = y == 0 ? 0 : y > 0 ? y - 1 : y + 1;
                int nearZ = z == 0 ? 0 : z > 0 ? z - 1 : z + 1;
                BlockPos nearbyLeaf = attachment.add(nearX, nearY, nearZ);
                if (canReplaceDreamwood(world, nearbyLeaf)) {
                    world.setBlockState(nearbyLeaf, leaves, 2);
                }
            }
        }
    }

    private boolean isAndwariCaveChunk(World world, int chunkX, int chunkZ) {
        // Match the reference structure set's 28-chunk spacing and
        // 8-chunk separation with a deterministic candidate per region.
        final int spacing = 28;
        final int separation = 8;
        int regionX = Math.floorDiv(chunkX, spacing);
        int regionZ = Math.floorDiv(chunkZ, spacing);
        long regionSeed = world.getSeed()
                ^ (regionX * 341873128712L)
                ^ (regionZ * 132897987541L)
                ^ 1328389907L;
        Random regionRandom = new Random(regionSeed);
        int targetX = regionX * spacing + separation
                + regionRandom.nextInt(spacing - separation);
        int targetZ = regionZ * spacing + separation
                + regionRandom.nextInt(spacing - separation);
        return chunkX == targetX && chunkZ == targetZ;
    }

    /**
     * Procedural 1.12 port of MythicBotany's Andwari Cave. It has a hidden
     * surface entrance, a descending livingrock stair tunnel, a gold-filled
     * chamber, and a chest with the fixed cursed ring plus random treasure.
     */
    private void generateAndwariCave(World world, Random random, int chunkX, int chunkZ) {
        EnumFacing direction = EnumFacing.HORIZONTALS[random.nextInt(
                EnumFacing.HORIZONTALS.length)];
        EnumFacing left = direction.rotateY();
        int localX = direction == EnumFacing.EAST ? 1
                : direction == EnumFacing.WEST ? 14 : 8;
        int localZ = direction == EnumFacing.SOUTH ? 1
                : direction == EnumFacing.NORTH ? 14 : 8;
        int x = chunkX * 16 + localX;
        int z = chunkZ * 16 + localZ;
        BlockPos surface = findGroundSurface(world, x, z);
        if (surface == null || surface.getY() < 16
                || world.getBiome(new BlockPos(x, 0, z)) != AlfheimBiomes.GOLDEN_FIELDS) {
            return;
        }

        BlockPos entrance = new BlockPos(x, surface.getY(), z);
        BlockPos roomFloor = offsetAndwari(entrance, direction, 10, left, 0, -10);
        IBlockState livingrock = vazkii.botania.common.block.ModBlocks.livingrock
                .getDefaultState();

        // Validate before changing blocks so structures and existing features
        // are not destroyed by a failed placement.
        for (int distance = 0; distance <= 10; distance++) {
            BlockPos step = offsetAndwari(entrance, direction, distance, left,
                    0, -distance);
            for (int lateral = -1; lateral <= 1; lateral++) {
                for (int vertical = 1; vertical <= 3; vertical++) {
                    if (!canCarveAndwari(world, offsetAndwari(step, direction,
                            0, left, lateral, vertical))) {
                        return;
                    }
                }
            }
            if (distance > 0 && !canCarveAndwari(world, step)) {
                return;
            }
        }
        for (int forward = -5; forward <= 5; forward++) {
            for (int lateral = -4; lateral <= 4; lateral++) {
                if (!canCarveAndwari(world, offsetAndwari(roomFloor, direction,
                        forward, left, lateral, 0))) {
                    return;
                }
                for (int vertical = 1; vertical <= 5; vertical++) {
                    if (!canCarveAndwari(world, offsetAndwari(roomFloor, direction,
                            forward, left, lateral, vertical))) {
                        return;
                    }
                }
            }
        }

        // Three-block-wide descending stair passage with livingrock walls.
        for (int distance = 0; distance <= 10; distance++) {
            BlockPos step = offsetAndwari(entrance, direction, distance, left,
                    0, -distance);
            for (int lateral = -1; lateral <= 1; lateral++) {
                for (int vertical = 1; vertical <= 3; vertical++) {
                    world.setBlockToAir(offsetAndwari(step, direction, 0, left,
                            lateral, vertical));
                }
            }
            if (distance > 0) {
                world.setBlockState(step, livingrock, 2);
            }
            for (int vertical = 1; vertical <= 3; vertical++) {
                world.setBlockState(offsetAndwari(step, direction, 0, left,
                        -2, vertical), livingrock, 2);
                world.setBlockState(offsetAndwari(step, direction, 0, left,
                        2, vertical), livingrock, 2);
            }
            world.setBlockState(offsetAndwari(step, direction, 0, left,
                    0, 4), livingrock, 2);
        }

        // Carve a five-block-high chamber with a solid livingrock floor.
        for (int forward = -5; forward <= 5; forward++) {
            for (int lateral = -4; lateral <= 4; lateral++) {
                BlockPos floor = offsetAndwari(roomFloor, direction, forward,
                        left, lateral, 0);
                world.setBlockState(floor, livingrock, 2);
                for (int vertical = 1; vertical <= 5; vertical++) {
                    world.setBlockToAir(offsetAndwari(roomFloor, direction,
                            forward, left, lateral, vertical));
                }
            }
        }

        // The chest is beneath the left-hand gold pile, as in the reference.
        BlockPos chestPos = offsetAndwari(roomFloor, direction, -2, left, -3, 1);
        placeAndwariChest(world, random, chestPos, direction);
        for (int height = 1; height <= 3; height++) {
            BlockPos gold = chestPos.up(height);
            if (world.isAirBlock(gold)) {
                world.setBlockState(gold, Blocks.GOLD_BLOCK.getDefaultState(), 2);
            }
        }
        for (int forward = -4; forward <= 4; forward++) {
            for (int lateral = -3; lateral <= 3; lateral++) {
                if (random.nextInt(3) != 0) {
                    continue;
                }
                BlockPos gold = offsetAndwari(roomFloor, direction, forward,
                        left, lateral, 1);
                if (world.isAirBlock(gold)) {
                    world.setBlockState(gold, Blocks.GOLD_BLOCK.getDefaultState(), 2);
                    if (random.nextInt(4) == 0 && world.isAirBlock(gold.up())) {
                        world.setBlockState(gold.up(), Blocks.GOLD_BLOCK.getDefaultState(), 2);
                    }
                }
            }
        }

        // Most entrances are partially buried, making the cave difficult to
        // spot; a gold block may also mark the entrance from outside.
        if (random.nextInt(4) == 0) {
            for (int dx = -1; dx <= 1; dx++) {
                for (int dz = -1; dz <= 1; dz++) {
                    BlockPos cover = entrance.add(dx, 1, dz);
                    if (world.isAirBlock(cover)) {
                        world.setBlockState(cover, livingrock, 2);
                    }
                }
            }
        }
        if (random.nextBoolean()) {
            BlockPos marker = entrance.offset(left, 2).up();
            if (world.isAirBlock(marker)) {
                world.setBlockState(marker, Blocks.GOLD_BLOCK.getDefaultState(), 2);
            }
        }
    }

    private void placeAndwariChest(World world, Random random, BlockPos pos,
                                   EnumFacing facing) {
        if (!world.isAirBlock(pos)) {
            return;
        }
        world.setBlockState(pos, Blocks.CHEST.getDefaultState()
                .withProperty(BlockChest.FACING, facing), 3);
        TileEntity tile = world.getTileEntity(pos);
        if (!(tile instanceof TileEntityChest)) {
            return;
        }
        TileEntityChest chest = (TileEntityChest) tile;
        chest.setInventorySlotContents(0, new ItemStack(ModItems.cursedAndwariRing));
        int rolls = 8 + random.nextInt(6);
        for (int roll = 0; roll < rolls; roll++) {
            int choice = random.nextInt(15);
            ItemStack loot;
            if (choice == 0) {
                loot = new ItemStack(Items.GOLDEN_APPLE, 1, 1);
            } else if (choice < 5) {
                loot = new ItemStack(Items.GOLDEN_APPLE, 1 + random.nextInt(3));
            } else if (choice < 10) {
                loot = new ItemStack(Items.GOLD_INGOT, 3 + random.nextInt(6));
            } else {
                loot = new ItemStack(Items.GOLD_NUGGET, 4 + random.nextInt(17));
            }
            chest.setInventorySlotContents(roll + 1, loot);
        }
        chest.markDirty();
    }

    private static BlockPos offsetAndwari(BlockPos origin, EnumFacing forward,
                                          int forwardDistance, EnumFacing lateral,
                                          int lateralDistance, int vertical) {
        return origin.add(
                forward.getXOffset() * forwardDistance
                        + lateral.getXOffset() * lateralDistance,
                vertical,
                forward.getZOffset() * forwardDistance
                        + lateral.getZOffset() * lateralDistance);
    }

    private boolean canCarveAndwari(World world, BlockPos pos) {
        if (pos.getY() <= 1 || pos.getY() >= world.getActualHeight()) {
            return false;
        }
        if (world.isAirBlock(pos)) {
            return true;
        }
        Block block = world.getBlockState(pos).getBlock();
        return block == vazkii.botania.common.block.ModBlocks.livingrock
                || block == Blocks.STONE
                || block == Blocks.DIRT
                || block == Blocks.GRASS
                || block == Blocks.GRAVEL
                || block == Blocks.SAND
                || block == Blocks.SANDSTONE
                || (block == vazkii.botania.common.block.ModBlocks.altGrass
                && block.getMetaFromState(world.getBlockState(pos)) == 1);
    }

    private boolean generateAbandonedApothecary(World world, Random random, int x, int z) {
        BlockPos surface = findGroundSurface(world, x, z);
        if (surface == null || !world.isAirBlock(surface.up())) {
            return false;
        }
        BlockPos base = surface.up();
        vazkii.botania.api.state.enums.AltarVariant variant =
                vazkii.botania.api.state.enums.AltarVariant.values()[
                        random.nextInt(vazkii.botania.api.state.enums.AltarVariant.values().length)];
        IBlockState altarState = vazkii.botania.common.block.ModBlocks.altar.getDefaultState()
                .withProperty(BotaniaStateProps.ALTAR_VARIANT, variant);
        world.setBlockState(base, altarState, 2);

        TileEntity tile = world.getTileEntity(base);
        if (!(tile instanceof vazkii.botania.common.block.tile.TileAltar)) {
            return false;
        }
        vazkii.botania.common.block.tile.TileAltar altar =
                (vazkii.botania.common.block.tile.TileAltar) tile;
        if (variant == vazkii.botania.api.state.enums.AltarVariant.MOSSY) {
            altar.isMossy = true;
        }
        if (random.nextInt(30) == 0) {
            altar.setLava(true);
        } else if (random.nextInt(4) != 0) {
            altar.setWater(true);
            int petals = random.nextInt(5);
            for (int slot = 0; slot < petals; slot++) {
                altar.getItemHandler().setStackInSlot(slot,
                        new net.minecraft.item.ItemStack(
                                vazkii.botania.common.item.ModItems.petal, 1,
                        random.nextInt(16)));
            }
        }
        altar.markDirty();
        return true;
    }
}
